# Configuration de la base de données PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=root
quarkus.datasource.password=hamza
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/banck

# Création automatique de la base de données si elle n'existe pas
quarkus.datasource.jdbc.additional-jdbc-properties."createDatabaseIfNotExist"=true
# Configuration Hibernate pour la gestion du schéma
quarkus.hibernate-orm.sql-load-script=no-file
# Logs SQL (optionnel - utile pour le développement)
quarkus.hibernate-orm.log.sql=true

