quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=root
quarkus.datasource.password=password123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/Banck?createDatabaseIfNotExist=true
quarkus.hibernate-orm.database.generation=update
